Setup of a few things
hungrysushi/ragnarok_game pull request #1
Opened 2018-01-22 17:58 UTC by hungrysushi

Added a top level CMakeLists
Added Gtest module
Set up barebones renderer directory

2018-01-23 01:19 UTC, ktadiko commented on renderer/CMakeLists.txt
> +
It might be better to put these in a directory called "engine"

2018-01-23 01:20 UTC, ktadiko requested changes
Everything looks good. Just put the renderer under engine.

2018-01-23 01:31 UTC, ktadiko commented on renderer/CMakeLists.txt
> +
Maybe "engine/graphics/renderer" even. Cause shaders, sprites could be added there too.

2018-01-23 11:04 UTC, hungrysushi commented on renderer/CMakeLists.txt
> +
I'm fine with putting it under engine, but nesting it 3 levels deep might be too much. Besides, I think sprites and other resources should really be in their own top level folder

2018-01-24 03:34 UTC, ktadiko approved these changes

2018-01-24 03:35 UTC, merged