A few more miscellaneous things
hungrysushi/ragnarok_game pull request #2
Opened 2018-01-25 16:53 UTC by hungrysushi

Created a bare main.cpp for the main app
Added a few more modules for the graphics
Added some vector types
Created a stub world class

Need to determine what else needs to be provided by the world and the renderer

2018-01-26 03:43 UTC, ktadiko requested changes
Everything looks great. Very small changes required.

2018-01-26 03:43 UTC, ktadiko commented on util/include/util/vec_types.h
> +};
:thumbsup:

2018-01-26 03:43 UTC, ktadiko commented on engine/world/include/world/world.h
> +
How about getDimesions() and getViewPos() instead?

2018-01-26 11:39 UTC, hungrysushi commented on engine/world/include/world/world.h
> +
Agreed

2018-01-26 12:50 UTC, atfreij reviewed
Agree with Kaush on naming scheme, everything else looks good.

2018-01-26 19:14 UTC, ktadiko commented on util/include/util/vec_types.h
> +};
Now that I think about. Name these vecXf , f representing floating point. We may need integer vectors later on.

2018-01-26 19:19 UTC, hungrysushi commented on util/include/util/vec_types.h
> +};
Most, if not all, of the math is done in floating point, though. When would we need a strictly integer vector?

Making the change, it certainly wouldn't hurt

2018-01-26 19:22 UTC, hungrysushi commented on util/include/util/vec_types.h
> +};
Rather than explicitly naming it, what do you think about templating it instead?
ie something like vec4<int>

2018-01-26 19:31 UTC, hungrysushi commented on engine/world/include/world/world.h
> +        vec3<float> GetDimensions();
Example of the templated struct

2018-01-29 16:19 UTC, ktadiko approved these changes
:100:

2018-01-29 16:19 UTC, merged