Implements base classes for the audio manager using OpenAL
hungrysushi/ragnarok_game pull request #3
Opened 2018-01-26 03:14 UTC by ktadiko

Device to get/set playback and capture devices
OpenAL Source Wrapper
OpenAL Listener Wrapper

2018-01-26 16:35 UTC, hungrysushi commented on engine/audio/CMakeLists.txt
> +add_library(renderer
Changing this later?

2018-01-26 16:35 UTC, hungrysushi commented on engine/audio/include/device.h
> +/* #include <AL/al.h> */
Is the OpenAL source available easily? It would be nice to have it available as a submodule, so we're all using the same version.

2018-01-26 16:38 UTC, hungrysushi commented on engine/audio/include/device.h
> +    private:
access modifiers same indentation as "class"
Also, public at the top

2018-01-26 16:40 UTC, hungrysushi commented on engine/audio/include/device.h
> +        ~Device();
I like the destructor and constructor together, but I'm not married to the idea if you like this better

2018-01-26 16:43 UTC, hungrysushi requested changes
Put the headers in includes/audio, that way it can be imported as "audio/listener.h," for example. Makes it easier to see where it came from

2018-01-26 16:47 UTC, hungrysushi commented
Everything else looks good to me :)

2018-01-26 18:58 UTC, ktadiko commented on engine/audio/CMakeLists.txt
> +add_library(renderer
I changed it. Looks like I didn't save it. Thanks for the catch

2018-01-26 18:59 UTC, ktadiko commented on engine/audio/include/device.h
> +    private:
:+1:

2018-01-26 19:02 UTC, ktadiko commented on engine/audio/include/device.h
> +        ~Device();
I have a very philosophical way of looking at it. What you take to construct it, the methods available after construction. And destructor at the very end when it's life comes to an end. 

In other words, I don't care lol

2018-01-26 19:04 UTC, ktadiko commented on engine/audio/include/device.h
> +/* #include <AL/al.h> */
I can look into it. I'm not too sure.

2018-01-26 19:10 UTC, ktadiko commented on engine/audio/include/device.h
> +/* #include <AL/al.h> */
Yes, that was my plan. That's the reason those dependencies are commented out. I'm thinking of adding openal-soft as a submodule. Read very good things about it. Besides using that, there would be no other good alternatives.

2018-01-28 19:36 UTC, hungrysushi commented on engine/audio/include/audio/openal_device.h
> +}
semicolon and close namespace. Also, put a comment after the namespace closing brackets: `}  // namespace Ragnarok`

2018-01-28 19:36 UTC, hungrysushi commented on engine/audio/include/audio/openal_listener.h
> +    ~Listener();
Move above

2018-01-28 19:37 UTC, hungrysushi commented on engine/audio/include/audio/openal_listener.h
> +}
Add namespace comment

2018-01-28 19:38 UTC, hungrysushi commented on engine/audio/include/audio/openal_source.h
> +    ~Source();
Move above

2018-01-28 19:38 UTC, hungrysushi commented on engine/audio/include/audio/openal_source.h
> +}
semicolon, namespace comment

2018-01-28 19:39 UTC, hungrysushi commented on engine/audio/src/openal_device.cpp
> +}
`//  namespace Ragnarok`

2018-01-28 19:41 UTC, hungrysushi commented on engine/audio/src/openal_source.cpp
> +}
namespace

2018-01-28 19:46 UTC, hungrysushi commented on engine/audio/include/audio/openal_listener.h
> +    void setPosition(float x, float y, float z);
Whenever possible, please give arguments the const modifier. Since these are setters and the passed arguments shouldn't be changing, it makes sense to do so here

2018-01-28 19:48 UTC, hungrysushi requested changes
Please try to build. I think some of the missing braces and semicolons might cause compilation errors

2018-01-30 02:48 UTC, ktadiko commented
@hungrysushi @atfreij please merge this PR if everything looks fine

2018-01-30 02:56 UTC, hungrysushi approved these changes

2018-01-30 02:57 UTC, merged